image: speedy/android

before_script:
  - chmod +x ./gradlew
  - export ANDROID_HOME=/lib/android-sdk-linux
  - export PATH=$PATH:/lib/android-sdk-linux/platform-tools/

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/
  tags:
    - java

unitTests:
  stage: test
  script:
    - ./gradlew test
  tags:
    - java

#functionalTests:
#  stage: test
#  script:
#    - apt-get install -yq kvm
#    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
#    - chmod +x android-wait-for-emulator
#    - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter sys-img-x86-google_apis-${ANDROID_COMPILE_SDK}
#    - echo no | android-sdk-linux/tools/android create avd -n test -t android-${ANDROID_COMPILE_SDK} --abi google_apis/x86
#    - android-sdk-linux/tools/emulator64-x86 -avd test -no-window -no-audio &
#    - ./android-wait-for-emulator
#    - adb shell input keyevent 82
#    - ./gradlew cAT
#  tags:
#    - java
